# fly.toml app configuration file generated for ph-mcp on 2025-07-06T19:34:14Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ph-mcp'
primary_region = 'jnb'

[build]

[env]
  PORT = "8080"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
